/**
 * Copyright 2022 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package stat

import (
	context "context"
	"net/http"

	"github.com/xmidt-org/tr1d1um/transaction"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// RequestStat provides a mock function with given fields: ctx, authHeaderValue, deviceID
func (_m *MockService) RequestStat(ctx context.Context, authHeaderValue string, deviceID string) (*transaction.XmidtResponse, error) {
	ret := _m.Called(ctx, authHeaderValue, deviceID)

	var r0 *transaction.XmidtResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *transaction.XmidtResponse); ok {
		r0 = rf(ctx, authHeaderValue, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.XmidtResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, authHeaderValue, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTr1d1umTransactor is an autogenerated mock type for the Tr1d1umTransactor type
type MockTr1d1umTransactor struct {
	mock.Mock
}

// Transact provides a mock function with given fields: _a0
func (_m *MockTr1d1umTransactor) Transact(_a0 *http.Request) (*transaction.XmidtResponse, error) {
	ret := _m.Called(_a0)

	var r0 *transaction.XmidtResponse
	if rf, ok := ret.Get(0).(func(*http.Request) *transaction.XmidtResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.XmidtResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
