// Code generated by mockery v2.6.0. DO NOT EDIT.

package stat

import (
	context "context"

	common "github.com/xmidt-org/tr1d1um/common"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// RequestStat provides a mock function with given fields: authHeaderValue, deviceID, ctx
func (_m *MockService) RequestStat(authHeaderValue string, deviceID string, ctx context.Context) (*common.XmidtResponse, error) {
	ret := _m.Called(authHeaderValue, deviceID, ctx)

	var r0 *common.XmidtResponse
	if rf, ok := ret.Get(0).(func(string, string, context.Context) *common.XmidtResponse); ok {
		r0 = rf(authHeaderValue, deviceID, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.XmidtResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, context.Context) error); ok {
		r1 = rf(authHeaderValue, deviceID, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
