// Code generated by mockery v2.6.0. DO NOT EDIT.

package stat

import (
	context "context"

	common "github.com/xmidt-org/tr1d1um/common"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// RequestStat provides a mock function with given fields: ctx, authHeaderValue, deviceID
func (_m *MockService) RequestStat(ctx context.Context, authHeaderValue string, deviceID string) (*common.XmidtResponse, error) {
	ret := _m.Called(ctx, authHeaderValue, deviceID)

	var r0 *common.XmidtResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *common.XmidtResponse); ok {
		r0 = rf(ctx, authHeaderValue, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.XmidtResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, authHeaderValue, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
