## SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
---
version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
    - ineffassign
  settings:
    errorlint:
      errorf: false
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test.go
      - path: main\.go            # Accept TLSClientConfig with InsecureSkipVerify
        text: 'G402:'
      - path: main\.go            # Accept pprof is automatically exposed
        text: 'G108:'
      - path: outboundSender\.go  # Accept sha1 for signature
        text: 'G505:'
      - path: .go                 # Accept deprecated packages for now.
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
