# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---

extends: default

ignore:
  - .release/helm/tr1d1um/templates/tr1d1um.yaml

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
    max-spaces-after: -1
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start:
    present: true
  empty-lines:
    max: 2
  hyphens:
    max-spaces-after: 1
  indentation:
    level: error
    indent-sequences: consistent
  line-length:
    level: warning
    max: 90
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values:
      - 'true'
      - 'false'
