FROM golang:alpine as builder
MAINTAINER Jack Murdock <jack_murdock@comcast.com>

WORKDIR /go/src/github.com/xmidt-org/tr1d1um

RUN apk add --update git curl

COPY . .

RUN go build -o tr1d1um_linux_amd64

FROM alpine

RUN apk --no-cache add ca-certificates
RUN mkdir -p /etc/tr1d1um
VOLUME /etc/tr1d1um

EXPOSE 8080

COPY --from=builder /go/src/github.com/xmidt-org/tr1d1um/tr1d1um_linux_amd64 /
COPY tr1d1um.yaml /
ENTRYPOINT ["/tr1d1um_linux_amd64"]
