// Code generated by mockery v1.0.0. DO NOT EDIT.
package translation

import http "net/http"
import mock "github.com/stretchr/testify/mock"
import wrp "github.com/Comcast/webpa-common/wrp"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// SendWRP provides a mock function with given fields: _a0, _a1
func (_m *MockService) SendWRP(_a0 *wrp.Message, _a1 string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*wrp.Message, string) *http.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*wrp.Message, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
