# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  release:
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@6e0c44c4b34fb2fab2147be519222e7bae11267d # v4.9.29
    secrets: inherit
