# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  release:
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@09d410f3b5d769151edcd99c7ad8f1498fb586be # v4.9.28
    secrets: inherit
