# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  release:
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@800eaf98146b4e8794feb6ba2b6d14484cb2498b # v4.9.30
    secrets: inherit
