# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@fa344ba8a1fc3e15f935e6715943a1c2674f05e8 # v4.9.42
    secrets: inherit
