# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@22a6e87c727e4ee31658bfa175e4124549703e11 # v4.9.46
    secrets: inherit
