# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  proj:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@216a9010316548a584f5ef6c2284bafa9e80296d # v4.9.43
    secrets: inherit
